name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Validate HTML
      run: |
        # Basic HTML validation
        python -c "
        import os
        import re
        
        # Check if index.html exists and has basic structure
        if os.path.exists('index.html'):
            with open('index.html', 'r', encoding='utf-8') as f:
                content = f.read()
                if '<!DOCTYPE html>' in content and '<html' in content:
                    print('✅ HTML structure valid')
                else:
                    print('❌ Invalid HTML structure')
                    exit(1)
        else:
            print('❌ index.html not found')
            exit(1)
        "
    
    - name: Validate CSS
      run: |
        # Basic CSS validation
        python -c "
        import os
        
        if os.path.exists('styles.css'):
            with open('styles.css', 'r', encoding='utf-8') as f:
                content = f.read()
                if len(content) > 0:
                    print('✅ CSS file exists and has content')
                else:
                    print('❌ CSS file is empty')
                    exit(1)
        else:
            print('❌ styles.css not found')
            exit(1)
        "
    
    - name: Validate JavaScript
      run: |
        # Basic JavaScript validation
        python -c "
        import os
        
        if os.path.exists('script.js'):
            with open('script.js', 'r', encoding='utf-8') as f:
                content = f.read()
                if 'function' in content and len(content) > 100:
                    print('✅ JavaScript file exists and has functions')
                else:
                    print('❌ JavaScript file seems incomplete')
                    exit(1)
        else:
            print('❌ script.js not found')
            exit(1)
        "
    
    - name: Check Model Files
      run: |
        # Check if model files exist
        python -c "
        import os
        
        required_files = ['credit_score_model.pkl', 'loan_data_1248_with_missing.csv']
        missing_files = []
        
        for file in required_files:
            if not os.path.exists(file):
                missing_files.append(file)
        
        if missing_files:
            print(f'⚠️  Warning: Missing files: {missing_files}')
        else:
            print('✅ All required model files present')
        "
    
    - name: Setup Pages
      uses: actions/configure-pages@v3
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: '.'
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
    
    - name: Verify Deployment
      run: |
        echo "🚀 Deployment completed!"
        echo "📱 Site URL: ${{ steps.deployment.outputs.page_url }}"
        echo "🔍 Check the deployment at: https://rohan911438.github.io/Credit-Score-Modelling/"
